name: "Build and Report Generation"
on: 
  push:
    branches : [main]
    paths:
      - '**'
      - '!docs/**'
      - '!**/*.md'
      - '!**/*.adoc'
  pull_request:
    paths:
      - '**'
      - '!docs/**'
      - '!**/*.md'
      - '!**/*.adoc'

jobs:
  test:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        java: [11]
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          submodules: recursive

      - name: Use Java ${{ matrix.java }}
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: ${{ matrix.java }}

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Test and Report
        env:
          DOKKA: false
          GRADLE_OPTS: -Dorg.gradle.jvmargs="-XX:MaxMetaspaceSize=1g"
        run: ./gradlew build --stacktrace